baseURL: "https://marcelbootsman.nl/"
title: Marcel Bootsman
paginate: 5
theme:
      - PaperMod
      - hugo-shortcode-gallery

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

googleAnalytics: 

permalinks:
  posts: :title/
  notes: notes/:title/

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Marcel Bootsman
    description: "ExampleSite description"
    keywords: [Blog, Portfolio, PaperModX]
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true

    assets:
        # disableFingerprinting: true
        favicon: "/img/marcelbootsman-logo.png"
        favicon16x16: "/img/marcelbootsman-logo.png"
        favicon32x32: "/img/marcelbootsman-logo.png"
        apple_touch_icon: "/img/marcelbootsman-logo.png"
        safari_pinned_tab: "</img/marcelbootsman-logo.png"

    label:
        text: "Marcel Bootsman"
        icon: /img/marcelbootsman-logo.png
        iconHeight: 44
        iconWidth: 40

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/mbootsman/marcelbootsman.nl/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    customcss:
      - "css/style.css"
menu:
    main:
        - identifier: archive
          name: Archive
          url: /archive/
          weight: 10
        - identifier: notes
          name: Notes
          url: /notes/
          weight: 20
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 40
# Read: https://github.com/reorx/hugo-PaperModX/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
