baseURL: "https://marcelbootsman.nl/"
title: Marcel Bootsman
paginate: 5
theme:
      - PaperMod
      - hugo-shortcode-gallery

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

googleAnalytics: 

permalinks:
  posts: :title/
  notes: notes/:title/

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

enableemoji: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Marcel Bootsman
    description: "Personal site of Marcel Bootsman. Here I share some WordPress, webdev, business and other stuff that interests me."
    keywords: 
    author: Marcel Bootsman
    # author: ["Me", "You"] # multiple authors
    images: ["/img/og-image.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true
    
    assets:
        # disableFingerprinting: true
        favicon: "/img/marcelbootsman-logo.png"
        favicon16x16: "/img/marcelbootsman-logo.png"
        favicon32x32: "/img/marcelbootsman-logo.png"
        apple_touch_icon: "/img/marcelbootsman-logo.png"
        safari_pinned_tab: "/img/marcelbootsman-logo.png"

    label:
        text: "Marcel Bootsman"
        icon: /img/marcelbootsman-logo.png
        iconHeight: 44
        iconWidth: 40

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/mbootsman/marcelbootsman.nl/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    customcss:
      - "css/style.css"

    hugoLeaflet:
      css:
      - href: "https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
        params:
          integrity: "sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
        crossorigin: ""
      - href: "https://unpkg.com/@raruto/leaflet-elevation@1.1.1/dist/leaflet-elevation.css"
      - href: "/css/leaflet.extra-markers.min.css"
      js:
      - src: "https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
        params:
          integrity: "sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
        crossorigin: ""
      - src: "/js/leaflet.elevation.js"
      - src: "/js/leaflet.hugo.js"
      - src: "/js/leaflet.extra-markers.min.js"
menu:
    main:
        - identifier: archive
          name: Archive
          url: /archive/
          weight: 10
        - identifier: notes
          name: Notes
          url: /notes/
          weight: 20
        - identifier: tweets
          name: Tweets
          url: /tweets/
          weight: 25
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 40
# Read: https://github.com/reorx/hugo-PaperModX/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
