baseURL = "/"
languageCode = "en-us"
title = "Marcel Bootsman"
theme = ["hello-friend", "hugo-shortcode-gallery"]
summaryLength = 20
paginate = 5

[permalinks]
  # Set permalink structure for posts
  posts = '/:title/'

[params]
   # if you set this to 0, only submenu trigger will be visible
   showMenuItems = 2

   # Show reading time in minutes for posts
   showReadingTime = true
   
   DateFormatList = "January 2, 2006"
[languages]
    [languages.en]
        copyright = ""

        [languages.en.params.logo]
        logoText = "Marcel Bootsman"
        logoHomeLink = "/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Allow "unsafe" HTML in md files
      unsafe = true

[menu]
[[menu.main]]
  identifier = 'archive'
  name = 'Archive'
  pre = ""
  url = '/archive/'